# Generated by Django 6.0.1 on 2026-01-11 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ethnicity_sect_tribe_agriculturalstatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subarea',
            old_name='Area',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='tybe',
            new_name='type',
        ),
        migrations.CreateModel(
            name='IndustrialZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('number_of_facilities', models.IntegerField(blank=True, null=True)),
                ('number_of_shops', models.IntegerField(blank=True, null=True)),
                ('number_of_workers', models.IntegerField(blank=True, null=True)),
                ('annual_revenue', models.IntegerField(blank=True, null=True)),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_industrial_zones', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industrial_zones', to='accounts.village')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('village', 'year'), name='uniq_industrial_zone_village_year')],
            },
        ),
    ]
