# Generated by Django 6.0.1 on 2026-02-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_area_subarea_area_rename_tybe_village_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villageethnicity',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
