# Generated by Django 6.0.1 on 2026-02-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_villageethnicity_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villagetribe',
            name='year',
        ),
    ]
