# Generated by Django 6.0.1 on 2026-02-09 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_villagetribe_year'),
    ]

    operations = [
        # 1) Drop safely (even if it doesn't exist)
        migrations.RunSQL(
            sql="ALTER TABLE accounts_villagetribe DROP CONSTRAINT IF EXISTS uniq_village_tribe_year;",
            reverse_sql=migrations.RunSQL.noop,
        ),

        # 2) Convert integer -> timestamptz safely using to_timestamp()
        #    Assuming stored integers are Unix timestamps in SECONDS.
        migrations.RunSQL(
            sql="""
                ALTER TABLE accounts_industrialzone
                ALTER COLUMN created_at TYPE timestamp with time zone
                    USING to_timestamp(created_at),
                ALTER COLUMN updated_at TYPE timestamp with time zone
                    USING to_timestamp(updated_at);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # 3) Now align Django model state (so Django knows these fields are DateTimeFields)
        migrations.AlterField(
            model_name='industrialzone',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='industrialzone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),

        # 4) Add the correct unique constraint (name should match fields)
        migrations.AddConstraint(
            model_name='villagetribe',
            constraint=models.UniqueConstraint(
                fields=('village', 'tribe'),
                name='uniq_village_tribe'
            ),
        ),
    ]
