# Generated by Django 6.0.1 on 2026-02-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_villagetribe_uniq_village_tribe_year_and_more'),
    ]

    operations = [
        # استخدم RunSQL بدلاً من RemoveConstraint للتأكد من أنه يتم تخطي الحذف إذا لم يكن الـ constraint موجودًا
        migrations.RunSQL(
            sql="ALTER TABLE accounts_industrialzone DROP CONSTRAINT IF EXISTS uniq_industrial_zone_village_year;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE accounts_villagetribe DROP CONSTRAINT IF EXISTS uniq_village_tribe_year;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE accounts_villagetribe DROP CONSTRAINT IF EXISTS uniq_village_tribe;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # إضافة الـ constraint الجديد
        migrations.AddConstraint(
            model_name='villagetribe',
            constraint=models.UniqueConstraint(fields=('village', 'tribe'), name='uniq_village_tribe_year'),
        ),
    ]

