# Generated by Django 6.0.1 on 2026-02-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_industrialzone_uniq_industrial_zone_village_year_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='industrialzone',
            constraint=models.UniqueConstraint(fields=('village', 'year'), name='uniq_industrial_zone_village_year'),
        ),
    ]
