# Generated by Django 6.0.1 on 2026-02-09 15:30

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_industrialzone_uniq_industrial_zone_village_year'),
    ]

    operations = [
        # استخدم RunSQL بدلاً من RemoveConstraint لتخطي الحذف إذا لم يكن الـ constraint موجودًا
        migrations.RunSQL(
            sql="ALTER TABLE accounts_villagetribe DROP CONSTRAINT IF EXISTS uniq_village_tribe_year;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE accounts_villagetribe DROP CONSTRAINT IF EXISTS uniq_village_tribe;",
            reverse_sql=migrations.RunSQL.noop,
        ),

        # تعديل حقل 'person' ليقبل null ويكون بلا قيمة افتراضية
        migrations.AlterField(
            model_name='commercialactivity',
            name='person',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
