# Generated by Django 6.0.1 on 2026-02-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_villagetribe_uniq_village_tribe_year_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE accounts_villagetribe DROP CONSTRAINT IF EXISTS uniq_village_tribe_year;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE accounts_villagetribe DROP CONSTRAINT IF EXISTS uniq_village_tribe;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='village',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
