# Generated by Django 6.0.1 on 2026-02-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_villagetribe_uniq_village_tribe_year_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='villagetribe',
            constraint=models.UniqueConstraint(fields=('village', 'tribe'), name='uniq_village_tribe_year'),
        ),
    ]
