# Generated by Django 6.0.1 on 2026-02-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_villagetribe_uniq_village_tribe_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agriculturalcrop',
            name='crop',
        ),
        migrations.AddField(
            model_name='agriculturalcrop',
            name='crop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
