# Generated by Django 6.0.1 on 2026-02-15 18:04
from django.db import migrations, models


def dedupe_for_new_uniques(apps, schema_editor):
    """
    Because we removed `year` and we are adding new UNIQUE constraints without `year`,
    there may be duplicates already in the DB. This step keeps the latest row (highest id)
    for each unique key and deletes the rest, so migration won't fail when adding constraints.
    """
    from django.db.models import Count

    def dedupe(Model, unique_fields):
        # find duplicate groups
        dup_groups = (
            Model.objects.values(*unique_fields)
            .annotate(c=Count("id"))
            .filter(c__gt=1)
        )

        for g in dup_groups:
            filters = {f: g[f] for f in unique_fields}
            ids = list(Model.objects.filter(**filters).order_by("-id").values_list("id", flat=True))
            # keep first (latest), delete others
            if len(ids) > 1:
                Model.objects.filter(id__in=ids[1:]).delete()

    AgriculturalCrop = apps.get_model("accounts", "AgriculturalCrop")
    AgriculturalStatus = apps.get_model("accounts", "AgriculturalStatus")
    DemographicData = apps.get_model("accounts", "DemographicData")
    GovernmentDepartment = apps.get_model("accounts", "GovernmentDepartment")
    IndustrialFacility = apps.get_model("accounts", "IndustrialFacility")
    IndustrialZone = apps.get_model("accounts", "IndustrialZone")
    VillageEthnicity = apps.get_model("accounts", "VillageEthnicity")
    VillageTribe = apps.get_model("accounts", "VillageTribe")

    # new uniques we are about to add:
    dedupe(AgriculturalCrop, ["agricultural_status", "crop_name"])
    dedupe(AgriculturalStatus, ["village", "season"])
    dedupe(DemographicData, ["village"])
    dedupe(GovernmentDepartment, ["village", "department_name"])
    dedupe(IndustrialFacility, ["village", "name"])
    dedupe(IndustrialZone, ["village"])
    dedupe(VillageEthnicity, ["village", "ethnicity"])
    dedupe(VillageTribe, ["village", "tribe"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_remove_agriculturalcrop_crop_and_more"),
    ]

    operations = [
        # -----------------------------
        # Drop old constraints safely (IF EXISTS) + keep Django state correct
        # -----------------------------
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "accounts_agriculturalcrop" DROP CONSTRAINT IF EXISTS "uniq_ag_status_crop";',
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="agriculturalcrop",
                    name="uniq_ag_status_crop",
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "accounts_agriculturalstatus" DROP CONSTRAINT IF EXISTS "uniq_agri_status_village_year_season";',
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="agriculturalstatus",
                    name="uniq_agri_status_village_year_season",
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "accounts_demographicdata" DROP CONSTRAINT IF EXISTS "uniq_demographic_village_year";',
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="demographicdata",
                    name="uniq_demographic_village_year",
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "accounts_governmentdepartment" DROP CONSTRAINT IF EXISTS "uniq_dept_village_year_name";',
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="governmentdepartment",
                    name="uniq_dept_village_year_name",
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "accounts_industrialfacility" DROP CONSTRAINT IF EXISTS "uniq_ind_facility_village_year_name";',
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="industrialfacility",
                    name="uniq_ind_facility_village_year_name",
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "accounts_industrialzone" DROP CONSTRAINT IF EXISTS "uniq_industrial_zone_village_year";',
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="industrialzone",
                    name="uniq_industrial_zone_village_year",
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "accounts_livestock" DROP CONSTRAINT IF EXISTS "uniq_livestock_village_year";',
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="livestock",
                    name="uniq_livestock_village_year",
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "accounts_villageethnicity" DROP CONSTRAINT IF EXISTS "uniq_village_ethnicity_year";',
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="villageethnicity",
                    name="uniq_village_ethnicity_year",
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "accounts_villagetribe" DROP CONSTRAINT IF EXISTS "uniq_village_tribe_year";',
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="villagetribe",
                    name="uniq_village_tribe_year",
                )
            ],
        ),

        # -----------------------------
        # Remove year fields (schema changes)
        # -----------------------------
        migrations.RemoveField(model_name="archaeologicalsite", name="year"),
        migrations.RemoveField(model_name="commercialactivity", name="year"),
        migrations.RemoveField(model_name="naturalasset", name="year"),
        migrations.RemoveField(model_name="tourismfacility", name="year"),

        migrations.RemoveField(model_name="agriculturalstatus", name="year"),
        migrations.RemoveField(model_name="demographicdata", name="year"),
        migrations.RemoveField(model_name="governmentdepartment", name="year"),
        migrations.RemoveField(model_name="industrialfacility", name="year"),
        migrations.RemoveField(model_name="industrialzone", name="year"),
        migrations.RemoveField(model_name="livestock", name="year"),
        migrations.RemoveField(model_name="villageethnicity", name="year"),

        # -----------------------------
        # Deduplicate data before adding new unique constraints
        # -----------------------------
        migrations.RunPython(dedupe_for_new_uniques, reverse_code=migrations.RunPython.noop),

        # -----------------------------
        # Add new constraints (without year)
        # -----------------------------
        migrations.AddConstraint(
            model_name="agriculturalcrop",
            constraint=models.UniqueConstraint(
                fields=("agricultural_status", "crop_name"),
                name="uniq_ag_status_crop",
            ),
        ),
        migrations.AddConstraint(
            model_name="agriculturalstatus",
            constraint=models.UniqueConstraint(
                fields=("village", "season"),
                name="uniq_agri_status_village_season",
            ),
        ),
        migrations.AddConstraint(
            model_name="demographicdata",
            constraint=models.UniqueConstraint(
                fields=("village",),
                name="uniq_demographic_village",
            ),
        ),
        migrations.AddConstraint(
            model_name="governmentdepartment",
            constraint=models.UniqueConstraint(
                fields=("village", "department_name"),
                name="uniq_dept_village_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="industrialfacility",
            constraint=models.UniqueConstraint(
                fields=("village", "name"),
                name="uniq_ind_facility_village_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="industrialzone",
            constraint=models.UniqueConstraint(
                fields=("village",),
                name="uniq_industrial_zone_village",
            ),
        ),
        migrations.AddConstraint(
            model_name="villageethnicity",
            constraint=models.UniqueConstraint(
                fields=("village", "ethnicity"),
                name="uniq_village_ethnicity",
            ),
        ),
        migrations.AddConstraint(
            model_name="villagetribe",
            constraint=models.UniqueConstraint(
                fields=("village", "tribe"),
                name="uniq_village_tribe",
            ),
        ),
    ]
