# Generated by Django 6.0.1 on 2026-02-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_agriculturalcrop_uniq_ag_status_crop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock',
            name='feeds',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='milk_products',
            field=models.TextField(blank=True, null=True),
        ),
    ]
