# Generated by Django 6.0.1 on 2026-02-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_livestock_feeds_alter_livestock_milk_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismfacility',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
