# Generated by Django 6.0.1 on 2026-02-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_tourismfacility_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='villagetribe',
            name='family_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
