# Generated by Django 6.0.1 on 2026-02-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_villagetribe_family_count'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agriculturalcrop',
            name='uniq_ag_status_crop',
        ),
        migrations.AddField(
            model_name='agriculturalstatus',
            name='crops',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='agriculturalcrop',
            name='agricultural_status',
        ),
        migrations.RemoveField(
            model_name='agriculturalcrop',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Crop',
        ),
        migrations.DeleteModel(
            name='AgriculturalCrop',
        ),
    ]
