# Generated by Django 6.0.1 on 2026-02-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_agriculturalcrop_uniq_ag_status_crop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculturalstatus',
            name='water_resources',
            field=models.CharField(blank=True, null=True),
        ),
    ]
