# Generated by Django 6.0.1 on 2026-02-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_agriculturalstatus_water_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentdepartment',
            name='ministry_name',
            field=models.CharField(max_length=32),
        ),
    ]
