# Generated by Django 6.0.1 on 2026-02-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_governmentdepartment_ministry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalasset',
            name='classification',
            field=models.CharField(choices=[('PROTECTED_AREA', 'Protected area'), ('TOURIST_SITE', 'Tourist site'), ('INVESTMENT_ZONE', 'Investment zone'), ('public_park', 'Public park'), ('FORESTRY_AREA', 'Forestry area'), ('NATURAL_RESOURCE', 'Natural resource')], max_length=64),
        ),
    ]
