# Generated by Django 6.0.1 on 2026-02-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_naturalasset_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalasset',
            name='classification',
            field=models.CharField(choices=[('protected_area', 'Protected area'), ('tourist_site', 'Tourist site'), ('investment_zone', 'Investment zone'), ('public_park', 'Public park'), ('forestry_area', 'Forestry area'), ('natural_resource', 'Natural resource')], max_length=64),
        ),
        migrations.AlterField(
            model_name='naturalasset',
            name='type',
            field=models.CharField(choices=[('water', 'Water'), ('forest', 'Forest'), ('reserve', 'Reserve'), ('mineral', 'Mineral'), ('mountain', 'Mountain'), ('coast', 'Coast'), ('desert', 'Desert'), ('nature_reserve', 'Nature reserve'), ('petroleum_resource', 'Petroleum Resource')], max_length=64),
        ),
        migrations.AlterField(
            model_name='tourismfacility',
            name='classification',
            field=models.CharField(blank=True, choices=[('local', 'Local'), ('national', 'National'), ('international', 'International')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tourismfacility',
            name='type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('esort', 'Resort'), ('TOURIST_RESTAURANT', 'Tourist restaurant'), ('park', 'Park'), ('ARCHAEOLOGICAL_SITE', 'Archaeological site'), ('beach', 'Beach'), ('museum', 'Museum')], max_length=64),
        ),
    ]
