# Generated by Django 6.0.1 on 2026-02-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_naturalasset_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismfacility',
            name='type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('esort', 'Resort'), ('tourist_restrant', 'Tourist restaurant'), ('park', 'Park'), ('archaeological_site', 'Archaeological site'), ('beach', 'Beach'), ('museum', 'Museum')], max_length=64),
        ),
    ]
