# Generated by Django 6.0.1 on 2026-01-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='area',
        ),
        migrations.RemoveField(
            model_name='subarea',
            name='Area',
        ),
        migrations.RemoveField(
            model_name='user',
            name='governorate',
        ),
        migrations.RemoveField(
            model_name='permissionrole',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='permissionrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subarea',
        ),
        migrations.RemoveField(
            model_name='village',
            name='subarea',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Governorate',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='PermissionRole',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='SubArea',
        ),
        migrations.DeleteModel(
            name='Village',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
